[workspace]
resolver = "2"
members = [
    "core",
    "elements",
    "http",
    "flac",
    "ogg",
    "mkv",
    "audio",
    "video",
    "scope",
    "pipewire",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/MAlba124/streamcraft"

[profile.bench]
debug = true
