#!/usr/bin/env python3
"""Bake the scope UI font atlas from JetBrains Mono (OFL-1.1).

Renders ASCII 0x20..=0x7E plus a synthesized replacement box, anti-aliased, at a
fixed set of pixel sizes, into one A8 atlas + a generated Rust metrics table. The
outputs are committed (`ui/font_atlas.a8`, `ui/font_data.rs`) so the crate ships a
real typeface with zero runtime dependencies and no build-time font pipeline.

Rerun (from the repo root) when changing sizes or the typeface:

    nix-shell -p "python3.withPackages (p: [p.pillow])" --run \
      "python3 scope/tools/bake_font.py \
         $(nix eval --raw nixpkgs#jetbrains-mono.outPath)/share/fonts/truetype/JetBrainsMono-Regular.ttf \
         scope/src/ui"

License: JetBrains Mono is (c) 2020 The JetBrains Mono Project Authors, SIL Open
Font License 1.1 — see scope/src/ui/FONT_LICENSE.txt (kept next to the outputs).
"""

import sys

from PIL import Image, ImageDraw, ImageFont

SIZES = [10, 12, 14, 18, 24, 32]
ATLAS_W = 512
PAD = 1  # transparent gutter between glyphs so linear filtering never bleeds

CHARS = [None] + [chr(c) for c in range(0x20, 0x7F)]  # index 0 = replacement box


def render_glyph(font, ch, px):
    """Return (L-image or None, off_x, off_y) for one glyph at one size."""
    if ch is None:
        # Replacement box: a hollow rectangle roughly matching digit metrics.
        w, h = max(3, int(px * 0.6)), max(4, int(px * 0.7))
        img = Image.new("L", (w, h), 0)
        d = ImageDraw.Draw(img)
        d.rectangle([0, 0, w - 1, h - 1], outline=255)
        return img, int(px * 0.1), int(px * 0.15)
    x0, y0, x1, y1 = font.getbbox(ch)
    if x1 <= x0 or y1 <= y0:  # space: no ink
        return None, 0, 0
    img = Image.new("L", (x1 - x0, y1 - y0), 0)
    ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255)
    return img, x0, y0


def main(ttf_path, out_dir):
    per_size = []
    shelf_x, shelf_y, shelf_h = PAD, PAD, 0
    placements = []  # (size_idx, glyph_idx, img, x, y, off_x, off_y)

    for px in SIZES:
        font = ImageFont.truetype(ttf_path, px)
        ascent, descent = font.getmetrics()
        advance = font.getlength("M")
        glyphs = []
        for gi, ch in enumerate(CHARS):
            img, off_x, off_y = render_glyph(font, ch, px)
            if img is None:
                glyphs.append((0, 0, 0, 0, 0, 0))
                continue
            w, h = img.size
            if shelf_x + w + PAD > ATLAS_W:
                shelf_x = PAD
                shelf_y += shelf_h + PAD
                shelf_h = 0
            placements.append((img, shelf_x, shelf_y))
            glyphs.append((shelf_x, shelf_y, w, h, off_x, off_y))
            shelf_x += w + PAD
            shelf_h = max(shelf_h, h)
        per_size.append((px, advance, ascent, ascent + descent, glyphs))

    atlas_h = shelf_y + shelf_h + PAD
    atlas = Image.new("L", (ATLAS_W, atlas_h), 0)
    for img, x, y in placements:
        atlas.paste(img, (x, y))

    with open(f"{out_dir}/font_atlas.a8", "wb") as f:
        f.write(atlas.tobytes())

    with open(f"{out_dir}/font_data.rs", "w") as f:
        f.write(
            "//! GENERATED by scope/tools/bake_font.py — do not edit by hand.\n"
            "//!\n"
            "//! Typeface: JetBrains Mono Regular 2.304, (c) 2020 The JetBrains Mono\n"
            "//! Project Authors — SIL Open Font License 1.1 (see FONT_LICENSE.txt).\n"
            "//! Anti-aliased A8 atlas; glyph 0 is the replacement box, 1..=95 are\n"
            "//! ASCII 0x20..=0x7E in order. `off_*` are the quad offsets from the\n"
            "//! pen (top-left of the line box); `advance`/`line_h` are per size.\n\n"
            f"pub const ATLAS_W: usize = {ATLAS_W};\n"
            f"pub const ATLAS_H: usize = {atlas_h};\n"
            'pub static ATLAS_A8: &[u8] = include_bytes!("font_atlas.a8");\n\n'
            "#[derive(Clone, Copy)]\n"
            "pub struct GlyphMetrics {\n"
            "    pub x: u16,\n    pub y: u16,\n    pub w: u16,\n    pub h: u16,\n"
            "    pub off_x: i16,\n    pub off_y: i16,\n}\n\n"
            "pub struct SizeMetrics {\n"
            "    pub px: f32,\n    pub advance: f32,\n    pub ascent: f32,\n"
            "    pub line_h: f32,\n    pub glyphs: [GlyphMetrics; 96],\n}\n\n"
            f"pub const NSIZES: usize = {len(SIZES)};\n\n"
            "pub static SIZES: [SizeMetrics; NSIZES] = [\n"
        )
        for px, advance, ascent, line_h, glyphs in per_size:
            f.write(
                f"    SizeMetrics {{ px: {px}.0, advance: {advance}, "
                f"ascent: {ascent}.0, line_h: {line_h}.0, glyphs: [\n"
            )
            for (x, y, w, h, ox, oy) in glyphs:
                f.write(
                    f"        GlyphMetrics {{ x: {x}, y: {y}, w: {w}, h: {h}, "
                    f"off_x: {ox}, off_y: {oy} }},\n"
                )
            f.write("    ] },\n")
        f.write("];\n")

    print(f"baked {len(SIZES)} sizes -> {ATLAS_W}x{atlas_h} A8 atlas "
          f"({ATLAS_W * atlas_h} bytes)")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
